USE [master]
GO

/****** Object:  Database [KwMobile]    Script Date: 08/12/2016 23:26:51 ******/
CREATE DATABASE [KwMobile] ON  PRIMARY 
( NAME = N'KwMobile', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\KwMobile.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'KwMobile_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\KwMobile_1.LDF' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [KwMobile] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KwMobile].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KwMobile] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KwMobile] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KwMobile] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KwMobile] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KwMobile] SET ARITHABORT OFF 
GO

ALTER DATABASE [KwMobile] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KwMobile] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [KwMobile] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KwMobile] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KwMobile] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KwMobile] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KwMobile] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KwMobile] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KwMobile] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KwMobile] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KwMobile] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KwMobile] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KwMobile] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KwMobile] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KwMobile] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KwMobile] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KwMobile] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KwMobile] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KwMobile] SET  READ_WRITE 
GO

ALTER DATABASE [KwMobile] SET RECOVERY FULL 
GO

ALTER DATABASE [KwMobile] SET  MULTI_USER 
GO

ALTER DATABASE [KwMobile] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KwMobile] SET DB_CHAINING OFF 
GO


